config/routes.rb
Rails.application.routes.draw do

  resources :films, only: [:index, :show]
  # get "/films", to: 'films#index'
  # get '/films/:id', to: 'films#show', id: /\d/

  resources :characters, only: [:index, :show] do
    collection do
      get 'search_results'
    end
  end
  # get '/characters/:id', to: 'characters#show', id: /\d/
  # get '/characters', to: 'characters#index'

  resources :planets, only: [:index, :show]
  # get '/planets/:id', to: 'planets#show', id: /\d/
  # get '/planets', to: 'planets#index'

  resources :races, only: [:index, :show]
  # get '/races/:id', to: 'races#show', id: /\d/
  # get '/races', to: 'races#index'

  get 'about', to: 'pages#about', as: 'about'

  root to: 'films#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  has_and_belongs_to_many :films
  belongs_to :planet
  belongs_to :race

  validates :name, :gender, presence: true
  validates :name, length: { minimum: 2 }

  paginates_per 6
end

app/models/characters_film.rb
class CharactersFilm < ApplicationRecord
  belongs_to :character
  belongs_to :film
end

app/models/film.rb
class Film < ApplicationRecord
  has_and_belongs_to_many :characters
  has_and_belongs_to_many :planets
  has_and_belongs_to_many :races

  validates :name, :director, :producer, :release_date, :opening_crawl,  presence: true
  validates :episodeID, numericality: { only_integer: true }

  paginates_per 6
end

app/models/films_planet.rb
class FilmsPlanet < ApplicationRecord
  belongs_to :film
  belongs_to :planet
end

app/models/films_race.rb
class FilmsRace < ApplicationRecord
  belongs_to :film
  belongs_to :race
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :characters
  has_and_belongs_to_many :films

  validates :name, :climate, presence: true
  validates :name, length: { minimum: 2 }

  paginates_per 6
end

app/models/race.rb
class Race < ApplicationRecord
  has_many :characters
  has_and_belongs_to_many :films

  validates :name, :language, presence: true
  validates :name, length: { minimum: 2 }

  paginates_per 6
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.order(:id).page(params[:page])
  end

  def show
    @character = Character.find(params[:id])
  end

  #GET /characters/search_results
  def search_results
    @query = params[:query]
    @characters = Character.where('name LIKE ?', "%#{@query}%").page(params[:page])
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.order(:id).page(params[:page])
  end

  def show
    @film = Film.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.order(:id).page(params[:page])
  end

  def show
    @planet = Planet.find(params[:id])
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  def index
    @races = Race.order(:id).page(params[:page])
  end

  def show
    @race = Race.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/characters/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>Star Wars Characters</h1>
    <p></p>
  </div>
</section>
<div class="album py-5 bg-light">
  <div class="container">
    <%= paginate @characters %>
    <div class="row">
      <% @characters.each do |character| %>
      <div class="col-md-2 mb-4">
        <div class="card h-100 mb-4 shadow-sm">
          <%= link_to (image_tag "#{character.id}.jpg", :class => "card-img-top", :alt => "#{character.name} image"), character %>
          <div class="card-body">
            <p class="card-text text-center"><%= character.name %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/characters/search_results.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>Your search for '<%= @query %>' returned <%= pluralize(@characters.size, 'result') %>.</h1>
    <p></p>
  </div>
</section>
<div class="album py-5 bg-light">
  <div class="container">
    <%= paginate @characters %>
    <div class="row">
      <% @characters.each do |character| %>
      <div class="col-md-2 mb-4">
        <div class="card h-100 mb-4 shadow-sm">
          <%= link_to (image_tag "#{character.id}.jpg", :class => "card-img-top", :alt => "#{character.name} image"), character %>
          <div class="card-body">
            <p class="card-text text-center"><%= character.name %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/characters/show.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>Characters Details</h1>
    <p></p>
  </div>
</section>
<div class="ml-5">
  <div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <%= image_tag "#{@character.id}.jpg", :class => "card-img", :alt => "#{@character.name} image" %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= @character.name %></h5>
          <p class="card-text mb-1"><small><strong>Birth Year: </strong><%= @character.birth_year %></small></p>
          <p class="card-text mb-1"><small><strong>Race: </strong><%= link_to @character.race.name, "/races/#{@character.race.id}" %></small></p>
          <p class="card-text mb-1"><small><strong>Height: </strong><%= @character.height %></small></p>
          <p class="card-text mb-1"><small><strong>Mass: </strong><%= @character.mass %></small></p>
          <p class="card-text mb-1"><small><strong>Gender: </strong><%= @character.gender %></small></p>
          <p class="card-text mb-1"><small><strong>Planet: </strong><%= link_to @character.planet.name, "/planets/#{@character.planet.id}" %></small></p>
        </div>
      </div>
    </div>
  </div>
</div>
<p class="ml-5"><%= link_to 'Back', characters_path%></p>
<div class="container">
  <div class="row">
    <% @character.films.each do |film| %>
    <div class="col-md-3 mb-4">
      <div class="card m-5">
        <%= link_to (image_tag "F#{film.id}.jpg", :class => "card-img-top", :alt => "#{film.name}"), film %>
        <div class="card-body">
          <p class="card-text text-center"><%= film.name %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/films/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>Star Wars Films</h1>
    <p></p>
  </div>
</section>
<div class="album py-5 bg-light">
  <div class="container">
    <%= paginate @films %>
    <div class="row">
      <% @films.each do |film| %>
      <div class="col-md-2 mb-4">
        <div class="card h-100 mb-4 shadow-sm">
          <%= link_to (image_tag "F#{film.id}.jpg", :class => "card-img-top", :alt => "#{film.name} image" ), film %>
          <div class="card-body">
            <p class="card-text text-center"><%= film.name %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/films/show.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>Film Details</h1>
    <p></p>
  </div>
</section>
<div class="ml-5">
  <div class="card mb-3" style="max-width: 800px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <%= image_tag "F#{@film.id}.jpg", :class => "card-img", :alt => "#{@film.name} image"%>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= @film.name %></h5>
          <p class="card-text mb-1"><small><strong>Episode </strong><%= @film.episodeID %></small></p>
          <p class="card-text mb-1"><small><strong>Release Date: </strong><%= @film.release_date %></small></p>
          <p class="card-text mb-1"><small><strong>Director: </strong><%= @film.director %></small></p>
          <p class="card-text mb-1"><small><strong>Producer: </strong><%= @film.producer %></small></p>
          <p class="card-text mb-1"><small><strong>Opening Crawl: </strong><%= @film.opening_crawl %></small></p>
        </div>
      </div>
    </div>
  </div>
</div>
<p><%= link_to 'Home', root_path %></p>
<div class= "row mt-5">
  <div class = "col-md-4">
    <div class="container">
      <h5>Characters</h5>
      <div class="row">
        <% @film.characters.each do |character| %>
        <div class="col-md-4">
          <div class="card m-2">
            <%= image_tag "#{character.id}.jpg", :class => "card-img-top", :alt => "#{character.name} image" %>
            <div class="card-body">
              <p class="card-text text-center"><%= link_to character.name, character %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class = "col-md-4">
    <div class="container">
    <h5>Planets</h5>
      <div class="row">
        <% @film.planets.each do |planet| %>
        <div class="col-md-4">
          <div class="card m-2">
            <%= link_to (image_tag "P#{planet.id}.jpg", :class => "card-img-top", :alt => "#{planet.name} image"), planet %>
            <div class="card-body">
              <p class="card-text text-center"><%= planet.name %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class = "col-md-4">
    <div class="container">
    <h5>Races</h5>
      <div class="row">
        <% @film.races.each do |race| %>
        <div class="col-md-4">
          <div class="card m-2">
            <%= image_tag "R#{race.id}.jpg", :class => "card-img-top", :alt => "#{race.name} image" %>
            <div class="card-body">
              <p class="card-text text-center"><%= link_to race.name, race %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <title>Star Wars Wiki-Fan</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href=<%= films_path %>>
        <%= image_tag "baby_yoda.png", width: "40", height: "40", :alt => "baby yoda image" %>
      </a>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

        <li class="nav-item active">
          <a class="nav-link" href=<%= films_path %>>Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= films_path %>>Films</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= characters_path %>>Characters</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= planets_path %>>Planets</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= races_path %>>Races</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= about_path %>>About Us</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0" action="/characters/search_results">
        <input class="form-control mr-sm-2" id="query" name="query" type="search" placeholder="Search" aria-label="Search">
        <select class="form-control form-control-md mr-2">
          <% races = Race.all %>
          <% races.each do |race|%>
            <option><%= race.name %></option>
          <% end %>
        </select>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>

    </div>
  </nav>
  <%= yield %>

<footer class="text-muted text-center mt-5">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>
      Star Wars and all associated names and/or images are copyright Lucasfilm Ltd. Images from Wookiepedia.
    </p>
    <p>
      Copyright © 2020 Sandro Campos.
    </p>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

app/views/pages/about.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>About</h1>
    <p></p>
  </div>
</section>
<div class="container" style= "width: 1000px;">
  <div class= "row" style= "width: 1000px;">
    <div class="col">
      <h4 class="text-center mb-5">Data Description</h4>
      <p class="text-justify">
        The API used is a base URL - <strong>"https://swapi.co/api/"</strong>. It is the root URL for all of the API.<br><br>
        JSON is the standard data format provided by SWAPI by default. All resources support JSON Schema.
        Making a request to /api/RESOURCE/schema will give you the details of that resource. This will allow
        you to programmatically inspect the attributes of that resource and their types.
        </p>

        <br>
        My Database consists in four tables: Films, Characters, Races, Planets.
        Using One-to-many and Many-to-many relationships.<br>
        <br>
        <h5>TABLES and COLUMNS:</h5>
        <p>
        -Films> id, title, episodeID, director, producer, released date, opening crawl, image.<br>
        -Races> id, name, classification, avg height, avg lifespan, language, image.<br>
        -Characters> id, name, gender, height, mass, birth_year, image.<br>
        -Planets> id, name, population, diameter, climate, image.<br>
        -Every single table has> created_at, updated_at columns.
        </p>
        <br><br>
        <h5>HOW ?</h5>
        <p>

        In order to create my own database, I planned first:<br>
        - extract data from all four tables.<br>
        - during the extract of each table, create my own 4 tables.<br>
        - creating the many-to-many relationship from these tables<br>
        - finalize adding the images in my database.
        </p>
        <br>

    </div>
    <div class="col-6">
      <h4 class="text-center mb-5">ERD Diagram</h4>
      <%= image_tag "erd.jpg", class: "ml-5", :alt => "ERD Diagram image" %>
    </div>
  </div>
</div>

app/views/planets/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>Star Wars Planets</h1>
    <p></p>
  </div>
</section>
<div class="album py-5 bg-light">
  <div class="container">
   <%= paginate @planets %>
    <div class="row">
      <% @planets.each do |planet| %>
      <div class="col-md-2 mb-4">
        <div class="card h-100 mb-4 shadow-sm">
          <%= link_to (image_tag "P#{planet.id}.jpg", :class => "card-img-top", :alt => "#{planet.name}"), planet %>
          <div class="card-body">
            <p class="card-text text-center"><%= planet.name %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/planets/show.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>Planet Details</h1>
    <p></p>
  </div>
</section>
<div class="ml-5">
  <div class="card mb-3" style="max-width: 800px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <%= image_tag "P#{@planet.id}.jpg", :class => "card-img", :alt => "#{@planet.name} image" %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= @planet.name %></h5>
          <p class="card-text mb-1"><small><strong>Population: </strong><%= @planet.population %></small></p>
          <p class="card-text mb-1"><small><strong>Diameter: </strong><%= @planet.diameter %></small></p>
          <p class="card-text mb-1"><small><strong>Climate: </strong><%= @planet.climate %></small></p>
        </div>
      </div>
    </div>
  </div>
</div>
<p class="ml-5"><%= link_to 'Home', root_path %></p>
<div class= "row mt-5">
  <div class = "col-md-6">
    <div class="container">
      <h5>Characters</h5>
      <div class="row">
        <% @planet.characters.each do |character| %>
        <div class="col-md-3">
          <div class="card m-4">
            <%= link_to (image_tag "#{character.id}.jpg", :class => "card-img-top", :alt => "#{character.name} image"), character %>
            <div class="card-body">
              <p class="card-text text-center"><%= character.name %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class = "col-md-6">
    <div class="container">
      <h5>Films</h5>
      <div class="row">
        <% @planet.films.each do |film| %>
        <div class="col-md-3">
          <div class="card m-4">
            <%= link_to (image_tag "F#{film.id}.jpg", :class => "card-img-top", :alt => "#{film.name} image"), film %>
            <div class="card-body">
              <p class="card-text text-center"><%= film.name %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/races/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>Star Wars Races</h1>
    <p></p>
  </div>
</section>
<div class="album py-5 bg-light">
  <div class="container">
   <%= paginate @races %>
    <div class="row">
      <% @races.each do |race| %>
      <div class="col-md-2 mb-4">
        <div class="card h-100 mb-4 shadow-sm">
          <%= link_to (image_tag "R#{race.id}.jpg", :class => "card-img-top", :alt => "#{race.name}"), race %>
          <div class="card-body">
            <p class="card-text text-center"><%= race.name %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/races/show.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>Race Details</h1>
    <p></p>
  </div>
</section>
<div class="ml-5">
  <div class="card mb-3" style="max-width: 600px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <%= image_tag "R#{@race.id}.jpg", :class => "card-img", :alt => "#{@race.name} image" %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= @race.name %></h5>
          <p class="card-text mb-1"><small><strong>Classification: </strong><%= @race.classification %></small></p>
          <p class="card-text mb-1"><small><strong>Avg Height: </strong><%= @race.average_height %></small></p>
          <p class="card-text mb-1"><small><strong>Avg Lifespan: </strong><%= @race.average_lifespan %></small></p>
          <p class="card-text mb-1"><small><strong>Language: </strong><%= @race.language %></small></p>
        </div>
      </div>
    </div>
  </div>
</div>
<p class="ml-5"><%= link_to 'Back', races_path%></p>
<div class= "row mt-5">
  <div class = "col-md-6">
    <div class="container">
    <h5>Characters</h5>
      <div class="row">
        <% @race.characters.each do |character| %>
        <div class="col-md-3">
          <div class="card m-4">
            <%= link_to (image_tag "#{character.id}.jpg", :class => "card-img-top", :alt => "#{character.name} image"), character %>
            <div class="card-body">
              <p class="card-text text-center"><%= character.name %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class = "col-md-6">
    <div class="container">
    <h5>Films</h5>
      <div class="row">
        <% @race.films.each do |film| %>
        <div class="col-md-3">
          <div class="card m-4">
            <%= link_to (image_tag "F#{film.id}.jpg", :class => "card-img-top", :alt => "#{film.name} image"), film %>
            <div class="card-body">
              <p class="card-text text-center"><%= film.name %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>